### ISSUE TITLE
Cannot clone body after it is used

### ISSUE THREAD

**Issue by paulxuca** [PepperHQ/ios-device-check#8]
On this line https://github.com/PepperHQ/ios-device-check/blob/69ccdda3a91f5741cb205ca1268aa2159cbb26d7/src/api.ts#L69

If the json body is already consumed in the try block, this line will fail.

**Comment by dominicrathbone** [comment]
Thanks @paulxuca we have a pull request in to fix this now.

**Comment by dominicrathbone** [comment]
Fixed in version `2.1.0`

**Comment by chr4ss1** [comment]
same issue in UpdateDevice/ValidateDevice

**Comment by dominicrathbone** [comment]
@ChrisEelmaa Doh, thanks for pointing this out. Fixed in version 2.2.0.
